catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #empty string is the root path
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'), #the name is a kwarg
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/create', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('toys/', views.ToyIndex.as_view(), name='toy_index'),
    path('toys/create', views.ToyCreate.as_view(), name='toy_create'),
    path('toys/<int:pk>', views.ToyDetail.as_view(), name='toy_detail'),
    path('toys/<int:pk>/update', views.ToyUpdate.as_view(), name='toy_update'),
    path('toys/<int:pk>/delete', views.ToyDelete.as_view(), name='toy_delete'),
    path('cats/<int:cat_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('cats/<int:cat_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.color} {self.name}'
    
    def get_absolute_url(self):
        return reverse('toy_detail', kwargs={'pk': self.id})

class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id}) #building a path string


class Feeding(models.Model):
    MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner'),
    )
    date = models.DateField('feeding date') #feeding date is the text displayed on the new form
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ('-date',)

class Photo(models.Model):
    url = models.CharField(max_length=200)
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cat: {self.cat.name} @{self.url}"

main_app/forms.py
from django.forms import ModelForm #creates an html5 form from a model
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ('date', 'meal')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Cat, Toy, Photo
from .forms import FeedingForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


import boto3
import uuid

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'catcollector-0217-kaushik'
# Create your views here.

# Add the Cat class & list and view function below the imports

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def cats_index(request):
    cats = Cat.objects.filter(user=request.user) #authorization shows only cats associated with that user
    return render(request, 'cats/index.html', {'cats': cats})

@login_required
def cats_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    feeding_form = FeedingForm()
    toys_cat_doesnt_have = Toy.objects.exclude(id__in=cat.toys.all().values_list('id'))

    return render(request, 'cats/detail.html', {
        'cat': cat, 
        'feeding_form': feeding_form,
        'toys': toys_cat_doesnt_have
    })

@login_required
def add_feeding(request, cat_id):
    form = FeedingForm(request.POST)

    if form.is_valid():
        new_feeding = form.save(commit=False) #saves in memory and creates a new feeding object
        new_feeding.cat_id = cat_id
        new_feeding.save()

    return redirect('detail', cat_id=cat_id)
@login_required 
def assoc_toy(request, cat_id, toy_id):
    Cat.objects.get(id=cat_id).toys.add(toy_id)
    return redirect('detail', cat_id=cat_id)

@login_required
def add_photo(request, cat_id):
    photo_file = request.FILES.get('photo-file', None) #name of input tag in detail.html(photo-file)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
        s3.upload_fileobj(photo_file, BUCKET, key)
        url = f"{S3_BASE_URL}{BUCKET}/{key}"
        photo = Photo(url=url, cat_id=cat_id)
        photo.save()
    except Exception as error:
        print('something went wrong uploading to s3')
        print(error)
    
    return redirect('detail', cat_id=cat_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'invalid credentials'
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form':form, 'error':error_message})

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = ('name', 'age', 'breed', 'description')
    success_url = '/cats/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = ('breed', 'description', 'age')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = '/cats/'

class ToyIndex(LoginRequiredMixin, ListView):
    model = Toy

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = '__all__'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Cat Collector</h1>
<hr />
<p>Hire the Cat Collector! Here you can add cats, their feeding schedules, and toys they can play with.</p>

{% endblock %}

main_app/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Cat Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">  CatCollector</a>
            </li>
          </ul>
          <ul class="right">
            <!-- changes below -->
            {% if user.is_authenticated %}
            <li><a href="{% url 'index' %}">View All My Cats</a></li>
            <li><a href="{% url 'cats_create' %}">Add a Cat</a></li>
            <li><a href="{% url 'toy_index' %}">View All Toys</a></li>
            <li><a href="{% url 'toy_create' %}">Add a Toy</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="center">
        All Rights Reserved, © 2023 Cat Collector  
      </div>
    </footer>
  </body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Cat Details</h1>

<div class="row">
  <div class="col s6">
    
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description }}</p>
        {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
        {% else %}
        <p>Age: Kitten</p>
        {% endif %}
      </div>
        <div class="card-action">
          <a href="{% url 'cats_update' cat.id %}">Edit</a>
          <a href="{% url 'cats_delete' cat.id %}">Delete</a>
        </div>
    </div>
    {% for photo in cat.photo_set.all %}
      <img class="responsive-img" width="300" src="{{photo.url}}" alt="{{cat.name}}">
    {%empty%}
      <div class="card-panel teal-text center-align">No Photos</div>
    {%endfor%}
    <form 
      action="{%url 'add_photo' cat.id%}" 
      method="POST" 
      enctype="multipart/form-data"
      class="card_panel">
      {%csrf_token%}
      <input type="file" name="photo-file">
      <input type="submit" value="Upload Photo" class="btn blue">
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' cat.id %}" method="POST">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" value="Add Feeding" class="btn blue">
    </form>

    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
          <tr>
            <td>{{ feeding.date }}</td>
            <td>{{ feeding.get_meal_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{cat.name}}'s Toys</h3>
    {% if cat.toys.count %}
      {%for toy in cat.toys.all%}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            A <span class="{{toy.color.lower}}-text">{{toy.color}}</span> {{toy.name}}
          </span>
        </div>
      </div>
    {%endfor%}
    {%else%}
      <h5>{{cat.name}} doesn't have any toys yet</h5>
    {%endif%}
  </div>
  <div class="col s6">
    <h3>Available Toys</h3>
    {%if toys.count %}
      {%for toy in toys%}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span class="{{toy.color.lower}}-text">{{toy.color}}</span>{{toy.name}}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' cat.id toy.id%}" method="POST">
              {% csrf_token %}
              <input type="submit" value="Add" class="btn">
            </form>
          </div>
        </div>
      {%endfor%}
    {% else %}
    <h5>{{ cat.name }} Already Has All Toys Available</h5>
    {%endif%}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  const mealEl = document.getElementById('id_meal');

  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date,
    setDefaultDate: true,
    autoClose: true
  })
  M.FormSelect.init(mealEl)
</script>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

<h1>Cat List</h1>

{% for cat in cats %}
<div class="card">
    <a href="{% url 'detail' cat.id %}">
        <div class="card-content">
            <span class="card-title">{{ cat.name }}</span>
            <p>Breed: {{ cat.breed }}</p>
            <p>Description: {{ cat.description }}</p>
            {% if cat.age > 0 %}
            <p>Age: {{ cat.age }}</p>
            {% else %}
            <p>Age: Kitten</p>
            {% endif %}
        </div>
    </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to CatCollector</h1>


{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Cat</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' cat.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}
{% block content %}
<form action='' method='POST'>
    {% csrf_token %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Cat</h1>
    {% endif %}
    <table>
        {{form.as_table}}
    </table>
    <input type='submit' value='Submit' class='btn'/>
</form>



{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Toy</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'toy_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Detail</h1>
<div class="card">
    <div class="card-content">
        <span class="card-title">A <span class='{{object.color.lower}}-text'>{{object.color.capitalize}}</span> {{object.name}}</span>
    </div>
    <div class="card-action">
        <a href="{% url 'toy_update' object.id %}">Edit</a>
        <a href="{% url 'toy_delete' object.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>
    {% comment %} using materialize class  {% endcomment %}
    Edit<span class="card-title">A <span class='{{object.color.lower}}-text'>{{object.color.capitalize}}</span></span>
</h1>
{% else %}
<h1>Add New Toy</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn green" type="submit" value="Submit">
</form>

{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in object_list %}

<a href="{% url 'toy_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">A <span class='{{toy.color.lower}}-text'>{{toy.color.capitalize}}</span> {{toy.name}}</span>
        </div>
    </div>
</a>

{% endfor %}
{% endblock %}